version: 1.0
name: RemakeHypixelSkyblock
Authors: [OptimusChan, Itchs]
main: com.itech4kids.skyblock.Main
commands:
  sbmenu:
    description: Opens the Skyblock Main Menu.
  spawncm:
    description: Spawns a custom mob.
    aliases: [spawnmob, spawncustommob]
  setPlayerStat:
    description: Set's a player's stat.
    aliases: [setStat, stat]
  itembrowser:
    description: Opens the item browser menu.
    aliases: [ib, items]
  swordcategory:
    description: Opens the sword category in the item browser menu.
  swordcategory2:
    description: Opens the 2nd page of the Sword Category in the Item Browser menu.
  todolist:
    description: Opens the todo list menu.
    aliases: [todo]